language: node_js
node_js:
  - "4"
  
jdk:
  - oraclejdk8
  
addons:
  sonarcloud: true
  
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=baumannzone-github -Dsonar.projectKey=n-dronao -Dsonar.sources='./' -X

# npm install
